import type { ReactElement } from "react";
import Head from "next/head";
import type { NextPageWithLayout } from "../../_app";
import { AuthLayout } from "shared/components/layout/AuthLayout";
import { useAuth0 } from "@auth0/auth0-react";

const SignUp: NextPageWithLayout = () => {
  const { loginWithRedirect } = useAuth0();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => loginWithRedirect()}>Log In</button>
    </>
  );
};

SignUp.getLayout = (page: ReactElement) => {
  return <AuthLayout>{page}</AuthLayout>;
};

export default SignUp;
