import type { ReactElement } from "react";
import Head from "next/head";
import { LoginPage } from "components/page/auth/login";
import type { NextPageWithLayout } from "../../_app";
import { AuthLayout } from "shared/components/layout/AuthLayout";

const Login: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </>
  );
};

Login.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Login;
