import Head from "next/head";
import { LoginPage } from "components/page/auth/login";
import { AuthLayout } from "shared/components/layout/AuthLayout";
import { NextPage } from "next/types";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthLayout>
        <LoginPage />
      </AuthLayout>
    </>
  );
};

export default Login;
