import type { ReactElement } from "react";
import Head from "next/head";
import { HomeContainer } from "components/containers";
import type { NextPageWithLayout } from "./_app";
import { AuthLayout } from "shared/components/layout/AuthLayout";

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeContainer />
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Home;
