import type { ReactElement } from "react";
import Head from "next/head";
import { HomeContainer } from "components/page/home";
import type { NextPageWithLayout } from ".././_app";
import { SimpleLayout } from "shared/components/layout";
import { HeaderNavigation } from "components/layout/HeaderNavigation";
import { Anchor } from "shared/components/ui";
import Link from "next/link";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeContainer />
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <SimpleLayout
      header={<Anchor iconName="AngleLeft">Back</Anchor>}
      navigation={<HeaderNavigation />}
    >
      {page}
    </SimpleLayout>
  );
};

export default Home;
