import type { ReactElement } from "react";
import Head from "next/head";
import type { NextPageWithLayout } from ".././_app";
import { BackTitle, DefaultLayout } from "shared/components/layout";
import { HeaderNavigation } from "components/layout/HeaderNavigation";
import { EditPage } from "components/page/edit";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditPage />
    </>
  );
};

Home.getLayout = (page: ReactElement) => {
  return (
    <DefaultLayout
      header={<BackTitle></BackTitle>}
      navigation={<HeaderNavigation />}
    >
      {page}
    </DefaultLayout>
  );
};

export default Home;
